version: "3.7"

services:
  redis:
    image: redis:7.2
    volumes:
      - rdata:/data
    ports:
      - "6379:6379"
  database:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  # minio:
  #   image: quay.io/minio/minio
  #   volumes:
  #     - mdata:/data
  #   ports:
  #     - '9000:9000'
  #     - '9090:9090'
  #   environment:
  #     - MINIO_ROOT_USER=root
  #     - MINIO_ROOT_PASSWORD=rootuser
  #   command: server /data --console-address ":9090"
  #
  # email:
  #   image: axllent/mailpit
  #   ports:
  #     - '1025:1025'
  #     - '8025:8025'
  #   environment:
  #     MP_SMTP_AUTH_ACCEPT_ANY: 1
  #     MP_SMTP_AUTH_ALLOW_INSECURE: 1
  #
volumes:
  pgdata:
  rdata:
