# fly.toml app configuration file generated for gits on 2024-04-20T11:14:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gits'
primary_region = 'jnb'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'
  strategy = "bluegreen"

[env]
  PORT = '8080'
  TZ = 'Africa/Johannesburg'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[checks]
  [checks.gits_http_check]
    grace_period = "30s"
    interval = "30s"
    method = "get"
    path = "/healthz"
    port = 8080
    timeout = "10s"
    type = "http"
    [checks.gits_http_check.headers]
      Content-Type = "application/json"

  [checks.gits_tcp_check]
    grace_period = "30s"
    interval = "15s"
    port = 8080
    timeout = "10s"
    type = "tcp"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
