# fly.toml app configuration file generated for gits-prd on 2025-01-09T13:40:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gits-prd'
primary_region = 'jnb'
kill_signal = 'SIGTERM'

[build]

[deploy]
  strategy = 'bluegreen'
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'gits-prd.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

  [[http_service.checks]]
    interval = '1m0s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
