# fly.toml app configuration file generated for gits-staging on 2024-09-16T11:23:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gits-staging'
primary_region = 'jnb'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'
  strategy = 'bluegreen'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

  [[http_service.checks]]
    interval = '1m30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512'
