defmodule Gits.Repo.Migrations.AddIds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add :public_id, :text, null: false
    end
  end

  def down do
    alter table(:tickets) do
      remove :public_id
    end
  end
end
