defmodule Gits.Repo.Migrations.AvailabilityField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add :availability, :text, null: false, default: "open"
    end
  end

  def down do
    alter table(:tickets) do
      remove :availability
    end
  end
end
