defmodule Gits.Repo.Migrations.Tickettype do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ticket_types) do
      add :sale_starts_at, :naive_datetime, null: false
      add :sale_ends_at, :naive_datetime, null: false
      add :quantity, :bigint, null: false
      add :limit_per_user, :bigint, null: false
    end

    alter table(:events) do
      add :starts_at, :naive_datetime, null: false
      add :ends_at, :naive_datetime, null: false
    end
  end

  def down do
    alter table(:events) do
      remove :ends_at
      remove :starts_at
    end

    alter table(:ticket_types) do
      remove :limit_per_user
      remove :quantity
      remove :sale_ends_at
      remove :sale_starts_at
    end
  end
end
