defmodule Gits.Repo.Migrations.AssociateEventToVenue do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :venue_id,
          references(:venues,
            column: :id,
            name: "events_venue_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:events, "events_venue_id_fkey")

    alter table(:events) do
      remove :venue_id
    end
  end
end
