defmodule Gits.Repo.Migrations.ChangePublishedAtType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      modify :published_at, :utc_datetime
    end
  end

  def down do
    alter table(:events) do
      modify :published_at, :naive_datetime
    end
  end
end
