defmodule Gits.Repo.Migrations.AddUserSupportRoleField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:support_roles) do
      add :support, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:support_roles) do
      remove :support
    end
  end
end
