defmodule Gits.Repo.Migrations.PaymentMethodToBasket do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:baskets) do
      add :payment_method, :text
    end
  end

  def down do
    alter table(:baskets) do
      remove :payment_method
    end
  end
end
