defmodule Gits.Repo.Migrations.PlaceIdUnique do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:venues, [:google_place_id], name: "venues_place_id_index")
  end

  def down do
    drop_if_exists unique_index(:venues, [:google_place_id], name: "venues_place_id_index")
  end
end
