defmodule Gits.Repo.Migrations.Foo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :paystack_reference, :text
      add :paystack_authorization_url, :text
    end

    create table(:order_fees_splits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :integration, :decimal
      add :paystack, :decimal
      add :subaccount, :decimal

      add :order_id,
          references(:orders,
            column: :id,
            name: "order_fees_splits_order_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:order_fees_splits, "order_fees_splits_order_id_fkey")

    drop table(:order_fees_splits)

    alter table(:orders) do
      remove :paystack_authorization_url
      remove :paystack_reference
    end
  end
end
