defmodule Gits.Repo.Migrations.AddTimezoneToTicketAndEvent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      modify :sale_ends_at, :utc_datetime
      modify :sale_starts_at, :utc_datetime
    end

    alter table(:events) do
      modify :ends_at, :utc_datetime
      modify :starts_at, :utc_datetime
    end
  end

  def down do
    alter table(:events) do
      modify :starts_at, :naive_datetime
      modify :ends_at, :naive_datetime
    end

    alter table(:tickets) do
      modify :sale_starts_at, :naive_datetime
      modify :sale_ends_at, :naive_datetime
    end
  end
end
