defmodule Gits.Repo.Migrations.OrderStates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tickets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :order_id,
          references(:orders,
            column: :id,
            name: "tickets_order_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :ticket_type_id,
          references(:ticket_types,
            column: :id,
            name: "tickets_ticket_type_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:orders) do
      add :email, :citext

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:events,
            column: :id,
            name: "orders_event_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "anonymous"
    end
  end

  def down do
    drop constraint(:orders, "orders_event_id_fkey")

    alter table(:orders) do
      remove :state
      remove :archived_at
      remove :event_id
      remove :created_at
      remove :email
    end

    drop constraint(:tickets, "tickets_order_id_fkey")

    drop constraint(:tickets, "tickets_ticket_type_id_fkey")

    drop table(:tickets)
  end
end
