defmodule Gits.Repo.Migrations.FixColumnNameTypo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:accounts), :paystack_subbaccount_code, to: :paystack_subaccount_code

    alter table(:accounts) do
      modify :paystack_subaccount_code, :text
    end

    drop table(:billing_settings)
  end

  def down do
    alter table(:accounts) do
      modify :paystack_subbaccount_code, :text
    end

    rename table(:accounts), :paystack_subaccount_code, to: :paystack_subbaccount_code

    create table(:billing_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :paystack_subbaccount_code, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :account_id,
          references(:accounts,
            column: :id,
            name: "billing_settings_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
