defmodule Gits.Repo.Migrations.AddArchiveExtension do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :archived_at, :utc_datetime_usec
    end

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:users, [:email],
             where: "archived_at IS NULL",
             name: "users_unique_email_index"
           )

    alter table(:tickets) do
      add :archived_at, :utc_datetime_usec
    end

    alter table(:ticket_instances) do
      add :archived_at, :utc_datetime_usec
    end

    alter table(:events) do
      add :archived_at, :utc_datetime_usec
    end

    alter table(:accounts) do
      add :archived_at, :utc_datetime_usec
    end

    alter table(:account_roles) do
      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:account_roles) do
      remove :archived_at
    end

    alter table(:accounts) do
      remove :archived_at
    end

    alter table(:events) do
      remove :archived_at
    end

    alter table(:ticket_instances) do
      remove :archived_at
    end

    alter table(:tickets) do
      remove :archived_at
    end

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :archived_at
    end
  end
end