defmodule Gits.Repo.Migrations.InstanceOfTickets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ticket_instances, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :ticket_id,
          references(:tickets,
            column: :id,
            name: "ticket_instances_ticket_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "ticket_instances_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:ticket_instances, "ticket_instances_ticket_id_fkey")

    drop constraint(:ticket_instances, "ticket_instances_user_id_fkey")

    drop table(:ticket_instances)
  end
end