defmodule Gits.Repo.Migrations.AddUserSupportRole do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:support_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :jobs, :boolean, null: false, default: false
      add :users, :boolean, null: false, default: false
      add :accounts, :boolean, null: false, default: false
      add :events, :boolean, null: false, default: false
      add :tickets, :boolean, null: false, default: false
      add :ticket_instances, :boolean, null: false, default: false
      add :baskets, :boolean, null: false, default: false

      add :user_id,
          references(:users,
            column: :id,
            name: "support_roles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:support_roles, [:id, :user_id], name: "support_roles_user_role_index")
  end

  def down do
    drop_if_exists unique_index(:support_roles, [:id, :user_id],
                     name: "support_roles_user_role_index"
                   )

    drop constraint(:support_roles, "support_roles_user_id_fkey")

    drop table(:support_roles)
  end
end
