defmodule Gits.Repo.Migrations.AddProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text

      add :user_id,
          references(:users,
            column: :id,
            name: "profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:profiles, "profiles_user_id_fkey")

    drop table(:profiles)
  end
end