defmodule Gits.Repo.Migrations.AddRequiredFieldsToTicket do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      modify :allowed_quantity_per_user, :bigint, default: 1
      modify :price, :decimal
      add :total_quantity, :bigint, default: 100
      add :sale_starts_at, :naive_datetime
      add :sale_ends_at, :naive_datetime
    end
  end

  def down do
    alter table(:tickets) do
      remove :sale_ends_at
      remove :sale_starts_at
      remove :total_quantity
      modify :price, :bigint
      modify :allowed_quantity_per_user, :bigint, default: nil
    end
  end
end
