defmodule Gits.Repo.Migrations.AddAccountRole do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:account_roles, primary_key: false) do
      add :type, :text, null: false, default: "owner"

      add :user_id,
          references(:users,
            column: :id,
            name: "account_roles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :account_id,
          references(:accounts,
            column: :id,
            name: "account_roles_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:account_roles, "account_roles_user_id_fkey")

    drop constraint(:account_roles, "account_roles_account_id_fkey")

    drop table(:account_roles)
  end
end