defmodule Gits.Repo.Migrations.OrderRefundRecret do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :requested_refund_secret, :binary
    end
  end

  def down do
    alter table(:orders) do
      remove :requested_refund_secret
    end
  end
end
