defmodule Gits.Repo.Migrations.LocationNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :location_notes, :text
      add :location_is_private, :boolean, default: false
    end
  end

  def down do
    alter table(:events) do
      remove :location_is_private
      remove :location_notes
    end
  end
end
