defmodule Gits.Repo.Migrations.States do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:hosts) do
      add :verified_at, :utc_datetime
      add :suspended_at, :utc_datetime
      add :state, :text, null: false, default: "pending"
    end

    alter table(:events) do
      add :completed_at, :utc_datetime
      add :state, :text, null: false, default: "draft"
    end
  end

  def down do
    alter table(:events) do
      remove :state
      remove :completed_at
    end

    alter table(:hosts) do
      remove :state
      remove :suspended_at
      remove :verified_at
    end
  end
end
