defmodule Gits.Repo.Migrations.AssociateInviteToAccount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:account_invites) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :status

      modify :state, :text, default: "sent"

      add :account_id,
          references(:accounts,
            column: :id,
            name: "account_invites_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:account_invites, "account_invites_account_id_fkey")

    alter table(:account_invites) do
      remove :account_id
      modify :state, :text, default: "pending"
      # This is the `down` migration of the statement:
      #
      #     remove :status
      #

      add :status, :text, null: false, default: "pending"
    end
  end
end
