defmodule Gits.Repo.Migrations.ChangeKeypairTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:keypairs) do
      remove :public_key
      remove :private_key
      add :pk, :binary, null: false
      add :sk, :binary, null: false
    end
  end

  def down do
    alter table(:keypairs) do
      remove :sk
      remove :pk
      add :private_key, :text, null: false
      add :public_key, :text, null: false
    end
  end
end
