defmodule Gits.Repo.Migrations.AddMembers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "owner"

      add :user_id,
          references(:users,
            column: :id,
            name: "members_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :account_id, :uuid
    end

    create table(:accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:events) do
      modify :account_id,
             references(:accounts,
               column: :id,
               name: "events_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:events, "events_account_id_fkey")

    alter table(:events) do
      modify :account_id, :uuid
    end

    drop table(:accounts)

    drop table(:events)

    drop constraint(:members, "members_user_id_fkey")

    drop table(:members)
  end
end
