defmodule Gits.Repo.Migrations.CapturePaystackReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:baskets) do
      add :paystack_authorization_url, :text
      add :paystack_reference, :text
    end
  end

  def down do
    alter table(:baskets) do
      remove :paystack_reference
      remove :paystack_authorization_url
    end
  end
end
