defmodule Gits.Repo.Migrations.NewStateMachine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :archived_at, :utc_datetime_usec
    end

    alter table(:members) do
      add :archived_at, :utc_datetime_usec
    end

    alter table(:events) do
      add :archived_at, :utc_datetime_usec
    end

    alter table(:attendees) do
      add :archived_at, :utc_datetime_usec
    end

    alter table(:account_invites) do
      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "pending"
    end
  end

  def down do
    alter table(:account_invites) do
      remove :state
      remove :archived_at
    end

    alter table(:attendees) do
      remove :archived_at
    end

    alter table(:events) do
      remove :archived_at
    end

    alter table(:members) do
      remove :archived_at
    end

    alter table(:users) do
      remove :archived_at
    end
  end
end
