defmodule Gits.Repo.Migrations.AddSlugify do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :slug, :text
    end

    alter table(:accounts) do
      add :slug, :text
    end
  end

  def down do
    alter table(:accounts) do
      remove :slug
    end

    alter table(:events) do
      remove :slug
    end
  end
end
