defmodule Gits.Repo.Migrations.CheckingIn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add :admitted_at, :utc_datetime
      add :checked_in_at, :utc_datetime

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :attendee_id,
          references(:users,
            column: :id,
            name: "tickets_attendee_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :state, :text, null: false, default: "open"
    end

    alter table(:ticket_types) do
      add :check_in_enabled, :boolean, null: false, default: false
    end

    alter table(:orders) do
      modify :state, :text, default: "anonymous"
    end
  end

  def down do
    alter table(:orders) do
      modify :state, :text, default: "open"
    end

    alter table(:ticket_types) do
      remove :check_in_enabled
    end

    drop constraint(:tickets, "tickets_attendee_id_fkey")

    alter table(:tickets) do
      remove :state
      remove :attendee_id
      remove :updated_at
      remove :created_at
      remove :checked_in_at
      remove :admitted_at
    end
  end
end
