defmodule Gits.Repo.Migrations.AddVenueResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:venues, primary_key: false) do
      add :archived_at, :utc_datetime_usec
      add :id, :text, null: false, primary_key: true
      add :name, :text, null: false
      add :address, :text, null: false
      add :latitude, :float, null: false
      add :longitude, :float, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :account_id,
          references(:accounts,
            column: :id,
            name: "venues_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:account_invites) do
      modify :email, :citext
    end
  end

  def down do
    alter table(:account_invites) do
      modify :email, :citext
    end

    drop constraint(:venues, "venues_account_id_fkey")

    drop table(:venues)
  end
end
