defmodule Gits.Repo.Migrations.RemoveAmountFromBasket do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:baskets) do
      remove :amount
    end
  end

  def down do
    alter table(:baskets) do
      add :amount, :decimal, null: false
    end
  end
end
