defmodule Gits.Repo.Migrations.Media do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :poster, :text
    end
  end

  def down do
    alter table(:events) do
      remove :poster
    end
  end
end
