defmodule Gits.Repo.Migrations.PriceIsInCents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:tickets), :price, to: :price_in_cents

    alter table(:tickets) do
      modify :price_in_cents, :decimal
    end
  end

  def down do
    alter table(:tickets) do
      modify :price, :decimal
    end

    rename table(:tickets), :price_in_cents, to: :price
  end
end
