defmodule Gits.Repo.Migrations.SeperateBillingToEntity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:billing_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :paystack_subbaccount_code, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :account_id,
          references(:accounts,
            column: :id,
            name: "billing_settings_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:accounts) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :paystack_subbaccount_code
    end

    # 
  end

  def down do
    alter table(:accounts) do
      # This is the `down` migration of the statement:
      #
      #     remove :paystack_subbaccount_code
      #
      # 
      add :paystack_subbaccount_code, :text
    end

    # 
    drop constraint(:billing_settings, "billing_settings_account_id_fkey")

    drop table(:billing_settings)
  end
end
