defmodule Gits.Repo.Migrations.AddPaystackFieldToAccount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts) do
      add :paystack_subbaccount_code, :text
    end
  end

  def down do
    alter table(:accounts) do
      remove :paystack_subbaccount_code
    end
  end
end
