defmodule Gits.Repo.Migrations.AddSupportAdmins do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:support_admins, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "support_admins_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:hosts, [:handle], name: "hosts_handle_index")
  end

  def down do
    drop_if_exists unique_index(:hosts, [:handle], name: "hosts_handle_index")

    drop constraint(:support_admins, "support_admins_user_id_fkey")

    drop table(:support_admins)
  end
end
