defmodule Gits.Repo.Migrations.PriceToTicket do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add :price_in_cents, :bigint, null: false
    end
  end

  def down do
    alter table(:tickets) do
      remove :price_in_cents
    end
  end
end