defmodule Gits.Repo.Migrations.DescriptionTickets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ticket_types) do
      add :description, :text, null: false
    end
  end

  def down do
    alter table(:ticket_types) do
      remove :description
    end
  end
end
