defmodule Gits.Repo.Migrations.IntegerToDecimalBasket do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:baskets) do
      modify :amount, :decimal
    end
  end

  def down do
    alter table(:baskets) do
      modify :amount, :bigint
    end
  end
end
