defmodule Gits.Repo.Migrations.OrderTotal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :total, :decimal
    end
  end

  def down do
    alter table(:orders) do
      remove :total
    end
  end
end
