defmodule Gits.Repo.Migrations.InteractionsRelative do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:interactions) do
      add :viewer_id, :text

      add :user_id,
          references(:users,
            column: :id,
            name: "interactions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :event_id,
          references(:events,
            column: :id,
            name: "interactions_event_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:interactions, "interactions_user_id_fkey")

    drop constraint(:interactions, "interactions_event_id_fkey")

    alter table(:interactions) do
      remove :event_id
      remove :user_id
      remove :viewer_id
    end
  end
end
