defmodule Gits.Repo.Migrations.AddEndDateToEvent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :ends_at, :naive_datetime, null: false
    end
  end

  def down do
    alter table(:events) do
      remove :ends_at
    end
  end
end
