defmodule Gits.Repo.Migrations.AddTicketInvites do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ticket_invites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :receipient_email, :citext

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :ticket_id,
          references(:tickets,
            column: :id,
            name: "ticket_invites_ticket_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :customer_id,
          references(:customers,
            column: :id,
            name: "ticket_invites_customer_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "created"
    end
  end

  def down do
    drop constraint(:ticket_invites, "ticket_invites_ticket_id_fkey")

    drop constraint(:ticket_invites, "ticket_invites_customer_id_fkey")

    drop table(:ticket_invites)
  end
end
