defmodule Gits.Repo.Migrations.RefundRequestDate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      modify :state, :text, default: "open"
      add :requested_refund_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:orders) do
      remove :requested_refund_at
      modify :state, :text, default: "anonymous"
    end
  end
end
