defmodule Gits.Repo.Migrations.AddAddressField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:venues) do
      add :address, :text, null: false
    end
  end

  def down do
    alter table(:venues) do
      remove :address
    end
  end
end
