defmodule Gits.Repo.Migrations.Rehaul do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
  end

  def down do
  end
end
