defmodule Gits.Repo.Migrations.AddressFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:venues) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :longitude

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :latitude

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :address

      add :google_maps_uri, :text, null: false
      add :formatted_address, :text, null: false
      add :type, :text
    end
  end

  def down do
    alter table(:venues) do
      remove :type
      remove :formatted_address
      remove :google_maps_uri
      # This is the `down` migration of the statement:
      #
      #     remove :address
      #

      add :address, :text, null: false
      # This is the `down` migration of the statement:
      #
      #     remove :latitude
      #

      add :latitude, :float, null: false
      # This is the `down` migration of the statement:
      #
      #     remove :longitude
      #

      add :longitude, :float, null: false
    end
  end
end
