defmodule Gits.Repo.Migrations.DecimalToIntegerPriceInCents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      modify :price_in_cents, :bigint
    end
  end

  def down do
    alter table(:tickets) do
      modify :price_in_cents, :decimal
    end
  end
end
