defmodule Gits.Repo.Migrations.AndQuantityPerUserForTicket do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add :allowed_quantity_per_user, :bigint
    end
  end

  def down do
    alter table(:tickets) do
      remove :allowed_quantity_per_user
    end
  end
end
