defmodule Gits.Repo.Migrations.AddTestFieldToTicket do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add :test, :boolean, default: false
    end
  end

  def down do
    alter table(:tickets) do
      remove :test
    end
  end
end
