defmodule Gits.Repo.Migrations.RenameFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:keypairs), :pk, to: :public_key

    rename table(:keypairs), :sk, to: :secret_key

    alter table(:keypairs) do
      modify :secret_key, :binary
      modify :public_key, :binary
    end
  end

  def down do
    alter table(:keypairs) do
      modify :pk, :binary
      modify :sk, :binary
    end

    rename table(:keypairs), :secret_key, to: :sk

    rename table(:keypairs), :public_key, to: :pk
  end
end
