defmodule Gits.Repo.Migrations.AshPapertrailConfigForWebhooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:webhooks_versions) do
      add :version_action_name, :text, null: false
    end
  end

  def down do
    alter table(:webhooks_versions) do
      remove :version_action_name
    end
  end
end
