defmodule Gits.Repo.Migrations.RsvpConfirmationDate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:tickets), :checked_in_at, to: :rsvp_confirmed_at

    alter table(:tickets) do
      modify :rsvp_confirmed_at, :utc_datetime
    end
  end

  def down do
    alter table(:tickets) do
      modify :checked_in_at, :utc_datetime
    end

    rename table(:tickets), :rsvp_confirmed_at, to: :checked_in_at
  end
end
