defmodule Gits.Repo.Migrations.RsvpFlag do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:ticket_types), :check_in_enabled, to: :rsvp_enabled

    alter table(:ticket_types) do
      modify :rsvp_enabled, :boolean
    end
  end

  def down do
    alter table(:ticket_types) do
      modify :check_in_enabled, :boolean
    end

    rename table(:ticket_types), :rsvp_enabled, to: :check_in_enabled
  end
end
