defmodule Gits.Repo.Migrations.CompletedAtField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:support_tickets, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :subject, :text, null: false
    end

    create table(:support_conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders) do
      add :completed_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:orders) do
      remove :completed_at
    end

    drop table(:support_conversations)

    drop table(:support_tickets)
  end
end
