defmodule Gits.Repo.Migrations.MultipleActors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events_versions) do
      add :job_id,
          references(:oban_jobs,
            column: :id,
            name: "events_versions_job_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:events_versions, "events_versions_job_id_fkey")

    alter table(:events_versions) do
      remove :job_id
    end
  end
end
