defmodule Gits.Repo.Migrations.RemoveActor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:venues_versions) do
      remove :user_id
    end

    alter table(:tickets_versions) do
      remove :user_id
    end

    alter table(:ticket_types_versions) do
      remove :user_id
    end

    alter table(:hosts_versions) do
      remove :user_id
    end

    alter table(:events_versions) do
      remove :job_id
      remove :user_id
    end
  end

  def down do
    alter table(:events_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "events_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )

      add :job_id,
          references(:oban_jobs,
            column: :id,
            name: "events_versions_job_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    alter table(:hosts_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "hosts_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    alter table(:ticket_types_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "ticket_types_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    alter table(:tickets_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "tickets_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    alter table(:venues_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "venues_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end
  end
end
