defmodule Gits.Repo.Migrations.TicketReady do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      modify :state, :text, default: "ready"
    end
  end

  def down do
    alter table(:tickets) do
      modify :state, :text, default: "open"
    end
  end
end
