defmodule Gits.Repo.Migrations.AddCancellationReason do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :cancellation_reason, :text
    end
  end

  def down do
    alter table(:orders) do
      remove :cancellation_reason
    end
  end
end
