defmodule Gits.Repo.Migrations.UniqueRole do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:host_roles, [:host_id, :user_id],
             name: "host_roles_host_user_role_index"
           )
  end

  def down do
    drop_if_exists unique_index(:host_roles, [:host_id, :user_id],
                     name: "host_roles_host_user_role_index"
                   )
  end
end
