defmodule Gits.Repo.Migrations.LinkEventToWebhook do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:webhooks) do
      add :event_id,
          references(:events,
            column: :id,
            name: "webhooks_event_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:webhooks, "webhooks_event_id_fkey")

    alter table(:webhooks) do
      remove :event_id
    end
  end
end
