defmodule Gits.Repo.Migrations.AddHostInvitesResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:host_invites_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:host_invites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:host_invites_versions) do
      modify :version_source_id,
             references(:host_invites,
               column: :id,
               name: "host_invites_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:host_invites) do
      add :email, :citext, null: false
      add :type, :text
      add :accepted_at, :utc_datetime
      add :expired_at, :utc_datetime

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :role_id,
          references(:host_roles,
            column: :id,
            name: "host_invites_role_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :host_id,
          references(:hosts,
            column: :id,
            name: "host_invites_host_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "sent"
    end
  end

  def down do
    drop constraint(:host_invites, "host_invites_role_id_fkey")

    drop constraint(:host_invites, "host_invites_host_id_fkey")

    alter table(:host_invites) do
      remove :state
      remove :archived_at
      remove :host_id
      remove :role_id
      remove :updated_at
      remove :created_at
      remove :expired_at
      remove :accepted_at
      remove :type
      remove :email
    end

    drop constraint(:host_invites_versions, "host_invites_versions_version_source_id_fkey")

    alter table(:host_invites_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:host_invites)

    drop table(:host_invites_versions)
  end
end
