defmodule Gits.Repo.Migrations.AddImageResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "images_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :host_id,
          references(:hosts,
            column: :id,
            name: "images_host_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :event_id,
          references(:events,
            column: :id,
            name: "images_event_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :archived_at, :utc_datetime_usec
    end

    alter table(:events) do
      remove :poster
    end
  end

  def down do
    alter table(:events) do
      add :poster, :text
    end

    drop constraint(:images, "images_user_id_fkey")

    drop constraint(:images, "images_host_id_fkey")

    drop constraint(:images, "images_event_id_fkey")

    drop table(:images)
  end
end
