defmodule Gits.Repo.Migrations.ImageNameNotNull do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :avatar
    end

    alter table(:images) do
      modify :name, :text, null: false
    end
  end

  def down do
    alter table(:images) do
      modify :name, :text, null: true
    end

    alter table(:users) do
      add :avatar, :text
    end
  end
end
