on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: gits-stg
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --app gits-prd
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
